home/urls.py
"""Module home.urls"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name="home_page"),
    path('legal_notice/', views.LegalNoticeView.as_view(), name="legal_notice"),
]

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('user/', include('user.urls'), name='user'),
    path('products/', include('products.urls'), name='products'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
"""User urls"""
from django.urls import path
from . import views

urlpatterns = [
    path('my_account/', views.UserAccountView.as_view(), name="user_account"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout_user"),
    path('new/', views.NewAccountView.as_view(), name="new_account"),
    path('create_new/', views.NewAccountView.as_view(), name="create_new"),
    path('check_user_login/', views.CheckLoginView.as_view(), name="check_user_login"),
    path('email_verification/', views.CheckEmailView.as_view(), name="email_verification"),
    path('check_pwd/', views.CheckPwdView.as_view(), name="check_pwd"),
]

user/models.py
"""Module user.models"""
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _

from .validators import UsernameValidator


class UserManager(BaseUserManager):
    """
    Define a model manager for User model
    with username field facultative
    and email required
    """

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        # Send email
        user.email_user(
            'Bienvenue !',
            'Bienvenue sur la plateforme de comparaison de produits Pur Beurre !',
            from_email='no-reply@purbeurre.fr'
        )

        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""

        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_active', True) # Change to False if verification by mail

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('SuperUser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('SuperUser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser):
    """User model for Pur Beurre"""

    # Change Username validator
    username_validator = UsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters and digits only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    # Unique = True for email address
    email = models.EmailField(
        _('email address'),
        unique=True
    )

    # Email at username field
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

class Newsletter(models.Model):
    """OneToOne Field for mail newsletter"""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    newsletter = models.BooleanField(default=False)

user/forms.py
"""Module user.forms"""
from django import forms
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.safestring import mark_safe


class ConnectionForm(forms.Form):
    """Connection form"""
    prefix = "connect"
    user_login = forms.CharField(label="Email ou login")
    pwd = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)

    user_login.widget.attrs.update(
        {
            'class': 'form-control',
            'placeholder': 'Email ou login'
        }
    )
    pwd.widget.attrs.update(
        {
            'class': 'form-control',
            'placeholder': 'Mot de passe'
        }
    )

class NewForm(forms.Form):
    """New account form"""

    username_validator = UnicodeUsernameValidator()

    email = forms.EmailField(label="Email *")
    user_login = forms.CharField(
        max_length=150,
        validators=[username_validator],
        required=False
    )
    pwd = forms.CharField(
        label="Mot de passe *",
        widget=forms.PasswordInput
    )
    pwd_confirm = forms.CharField(
        label="Confirmation du mot de passe",
        widget=forms.PasswordInput
    )
    firstname = forms.CharField(
        label="Prénom",
        max_length=30,
        required=False,
    )
    lastname = forms.CharField(
        label="Nom",
        max_length=30,
        required=False,
    )
    string_cgu = "J'ai lu et j'accepte les <a href='#' target='_blank'>" \
                 "Conditions Générales d'Utilisation</a>."
    cgu = forms.BooleanField(
        label=mark_safe(string_cgu),
        required=True
    )
    newsletter = forms.BooleanField(
        label="Newsletter",
        required=False
    )

    email.widget.attrs.update(
        {
            'class': 'form-control is-invalid has-popover',
            'placeholder': 'Email',
            'data-content': """
            <div class="invalid-input">
                Veuillez entrer votre adresse mail.
            </div>
            """,
            'data-html': "true",
            'data-placement': "left",
            'data-container': "body"
        }
    )
    user_login.widget.attrs.update(
        {
            'class': 'form-control has-popover',
            'placeholder': 'Login',
            'data-content': """
            <div>
                Facultatif. Peut être utilisé comme identifiant de connexion.
            </div>
            """,
            'data-html': "true",
            'data-placement': "left",
            'data-container': "body"
        }
    )
    pwd.widget.attrs.update(
        {
            'class': 'form-control is-invalid has-popover',
            'placeholder': 'Mot de passe',
            'data-content': """
                <div class="invalid-input">Au moins 8 charactères</div>
                <div class="invalid-input">Au moins 1 lettre majuscule</div>
                <div class="invalid-input">Au moins 1 chiffre</div>
                <div class="invalid-input">Au moins 1 charactère spécial</div>
            """,
            'data-html': "true",
            'data-placement': "left",
            'data-container': "body"
        }
    )
    pwd_confirm.widget.attrs.update(
        {
            'class': 'form-control is-invalid',
            'placeholder': 'Veuillez retaper le mot de passe',
            'data-content': """
                <div class="invalid-input">Les mots de passe ne correspondent pas.</div>
            """,
            'data-html': "true",
            'data-placement': "left",
            'data-container': "body"
        }
    )
    firstname.widget.attrs.update(
        {
            'class': 'form-control',
            'placeholder': 'Prénom'
        }
    )
    lastname.widget.attrs.update(
        {
            'class': 'form-control',
            'placeholder': 'Nom'
        }
    )
    cgu.widget.attrs.update(
        {
            'class': 'form-check-input is-invalid'
        }
    )
    newsletter.widget.attrs.update(
        {
            'class': 'form-check-input'
        }
    )

    def clean(self):
        cleaned_data = super().clean()
        pwd = cleaned_data.get("pwd")
        pwd_confirm = cleaned_data.get("pwd_confirm")

        if pwd != pwd_confirm:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

user/views.py
"""User"""
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.password_validation import validate_password
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic.base import ContextMixin
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

from .forms import ConnectionForm, NewForm
from .models import User
from .validators import validate_username


class UserFormContext(ContextMixin):
    """User form"""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_user'] = ConnectionForm()
        return context


class LoginView(TemplateView):
    """View to login User"""

    template_name = "/"

    form_user = ConnectionForm()

    def post(self, request, **kwargs):
        """User login from HTML form"""

        user_login = request.POST.get('connect-user_login', False)
        password = request.POST.get('connect-pwd', False)
        user = authenticate(username=user_login, password=password)
        if user is not None and user.is_active:
            login(request, user)

            if request.META.get('HTTP_REFERER') is not None:
                redirect_path = request.META.get('HTTP_REFERER')
            else:
                redirect_path = '/'

            return redirect(redirect_path)
        else:
            return render(request, 'user/new_account.html')


class LogoutView(TemplateView):
    """Logout User"""

    template_name = "/"

    def get(self, request, **kwargs):

        logout(request)

        return redirect(self.template_name)


class UserAccountView(LoginRequiredMixin, TemplateView):
    """View to show user account"""

    template_name = "/"

    def get(self, request, **kwargs):

        form_user = ConnectionForm()

        return render(
            request,
            'user/user.html',
            {
                "form_user": form_user
            }
        )


class NewAccountView(TemplateView):
    """View to register new use"""

    template_name = "/"

    def get(self, request, **kwargs):
        """Access new account page"""

        form_new = NewForm()
        form_user = ConnectionForm()

        return render(
            request,
            'user/new_account.html',
            {
                "form_new": form_new,
                "form_user": form_user
            }
        )

    def post(self, request, **kwargs):
        """Register new user and redirect to user account"""

        data = {'ok': False}
        form_new = NewForm(request.POST)
        if form_new.is_valid():
            email = form_new.cleaned_data["email"]
            if CheckEmailView.check_email(self, email, check_available=True):
                pwd = form_new.cleaned_data["pwd"]
                pwd_confirm = form_new.cleaned_data["pwd_confirm"]
                user_login = form_new.cleaned_data["user_login"]
                if user_login == '':
                    user_login = email
                firstname = form_new.cleaned_data["firstname"]
                lastname = form_new.cleaned_data["lastname"]
                # newsletter = form_new.cleaned_data["newsletter"]
                user = User.objects.create_user(
                    email,
                    password=pwd,
                    username=user_login,
                    first_name=firstname,
                    last_name=lastname
                )
                user.save()
                data['ok'] = True
            else:
                data['email'] = False
        else:
            try:
                validate_email(form_new.cleaned_data["email"])
            except:
                data['email'] = False
            try:
                pwd = form_new.cleaned_data["pwd"]
                pwd_confirm = form_new.cleaned_data["pwd_confirm"]
                assert pwd == pwd_confirm
            except:
                data['pwd'] = False

        if data['ok']:
            new_user = authenticate(
                request,
                username=email,
                password=pwd
            )
            if new_user is not None:
                login(request, new_user)
                data['url'] = reverse('user_account')

        return JsonResponse(data)

@method_decorator(csrf_exempt, name="dispatch")
class CheckLoginView(TemplateView):
    """
    Login check :
        - If not taken
        - If format is correct
    """
    template = '/'

    def post(self, request, **kwargs):
        """Login user from HTML form"""
        user_login = request.POST.get("user_login")

        if User.objects.filter(username=user_login).exists():
            return HttpResponse('login not available')
        else:
            try:
                validate_username(user_login)
                return HttpResponse('login ok')
            except ValidationError:
                return HttpResponse('Incorrect login format')

@method_decorator(csrf_exempt, name="dispatch")
class CheckEmailView(TemplateView):
    """
    Email check :
        - If not taken
        - If format is correct
    """
    template = '/'

    def post(self, request, **kwargs):
        """Retrieve email from HTML form"""
        email = request.POST.get('email')

        if self.check_email(email):
            return HttpResponse("email ok")
        else:
            return HttpResponse("email nok")

    def check_email(self, email, check_available=False):
        """Email check usable out of view"""
        if check_available:
            if User.objects.filter(email=email).exists():
                return False
        try:
            validate_email(email)
            return True
        except ValidationError:
            return False


@method_decorator(csrf_exempt, name="dispatch")
class CheckPwdView(TemplateView):
    """
    Pwd check :
        - If not too common
        - If format is correct :
            - contains at least one capital
            - contains at least one digit
            - contains at least 8 caracters
            - contains at least one special caracter

    """
    template = '/'

    def post(self, request, **kwargs):
        """Retrieve password from HTML form"""
        pwd = request.POST.get("pwd")

        try:
            validate_password(pwd)
        except ValidationError as err:
            return HttpResponse(json.dumps(err.messages))
        else:
            return HttpResponse("Mot de passe OK")

user/templates/user/new_account.html
{% extends 'base.html' %}
{% load static %}

{% block head_links %}
    <!-- User CSS -->
    <link href="{% static 'user/css/user.css' %}" rel="stylesheet" />
    <link href="{% static 'user/css/footer.css' %}" rel="stylesheet" />

{% endblock head_links %}

{% block body %}
    <header class="masthead">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-10 align-self-end">
                    <h1 class="text-uppercase text-white font-weight-bold">Nouveau compte</h1>
                    <hr class="divider my-4" />
                </div>
                {% comment %} <div class="col-lg-8 align-self-baseline">
                    <h2 class="text-white-75 font-weight-light mb-5">
                        {{user.username}} / 
                        {{user.firstname}}
                    </h2>
                </div> {% endcomment %}
            </div>
        </div>
    </header>
    <!-- New account informations -->
    <section class="page-section" id="new_account">
        <div class="container">
            <h2 class="text-center mt-0">Création d'un compte utilisateur</h2>
            <hr class="divider my-4" />
            <div class="row d-flex justify-content-center">
                <div class="col-6">
                    <form method="post" id="form_new" data-new-account="{% url 'create_new' %}" >
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_email">Email *</label>
                            {{form_new.email}}
                            <small id="emailHelp" class="form-text text-muted">Obligatoire. A utiliser comme identifiant de connexion.</small>
                        </div>
                        <div class="form-group">
                            <label for="id_user_login">Login</label>
                            {{form_new.user_login}}
                            <small id="pwdHelp" class="form-text text-muted">Facultatif. Peut être utilisé à la place de l'email lors de la connexion.</small>
                        </div>
                        <div class="form-group">
                            <label for="id_pwd">Mot de passe *</label>
                            <div class="row d-flex align-items-center">
                                <div class="col-11">
                                    {{form_new.pwd}}
                                </div>
                                <div class="col-1 d-flex justify-content-center">
                                    <a role="button"
                                       title="Voir le mot de passe"
                                       id="show_pwd"
                                    >
                                        <i class="fas fa-eye fa-lg"></i>
                                    </a>
                                </div>
                            </div>
                            <small id="pwdHelp" class="form-text text-muted">Obligatoire.</small>
                        </div>
                        <div class="form-group">
                            <label for="id_pwd_confirm">Confirmation du mot de passe *</label>
                            <div class="row d-flex align-items-center">
                                <div class="col-11">
                                    {{form_new.pwd_confirm}}
                                </div>
                                <div class="col-1 d-flex justify-content-center">
                                    <a role="button"
                                       title="Voir le mot de passe"
                                       id="show_pwd_confirm"
                                    >
                                        <i class="fas fa-eye fa-lg"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_firstname">Prénom</label>
                            {{form_new.firstname}}
                            <small id="firstnameHelp" class="form-text text-muted">Facultatif</small>
                        </div>
                        <div class="form-group">
                            <label for="id_lastname">Nom</label>
                            {{form_new.lastname}}
                            <small id="lastnameHelp" class="form-text text-muted">Facultatif</small>
                        </div>
                        <div class='row d-flex justify-content-center mb-2'>
                            <div class='col-8'>
                                <div class="form-check mt-2">
                                    {{form_new.cgu}}
                                    <label class="form-check-label" for="id_cgu">{{form_new.cgu.label}}</label>
                                </div>
                                <div class="form-check mt-2">
                                    {{form_new.newsletter}}
                                    <label class="form-check-label" for="id_newsletter">Je souhaite m'inscrire à la newsletter pour recevoir toutes les dernières informations et bons plans de la part de <span class="font-italic font-weight-bold">Pur Beurre</span>.</label>
                                </div>
                            </div>
                        </div>
                        <div class="row d-flex justify-content-center">
                            <input type="submit"
                                   class="btn btn-success d-flex justify-content-center"
                                   id="btn_new"
                                   value="Créer le compte"
                            >
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock body %}

{% block script %}
    <!-- AJAX new account script -->
    <script src="{% static 'user/js/user.js' %}"></script>

{% endblock script %}

user/templates/user/user.html
{% extends 'base.html' %}
{% load static %}

{% block head_links %}
    <!-- User CSS -->
    <link href="{% static 'user/css/user.css' %}" rel="stylesheet" />
    <link href="{% static 'user/css/footer.css' %}" rel="stylesheet" />

{% endblock head_links %}

{% block body %}
    <header class="masthead">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-10 align-self-end">
                    <h1 class="text-uppercase text-white font-weight-bold">Mon compte</h1>
                    <hr class="divider my-4" />
                </div>
                <div class="col-lg-8 align-self-baseline">
                    <h2 class="text-white-75 font-weight-light mb-5">
                        Bonjour {{user.firstname}} !
                    </h2>
                </div>
            </div>
        </div>
    </header>
    <!-- User informations -->
    <section class="page-section" id="user_infos">
        <div class="container">
            <h2 class="text-center mt-0">Informations utilisateur</h2>
            <hr class="divider my-4" />
            <div class="row d-flex justify-content-between">
                <div class="col-6">
                    {{user.email}}
                </div>
            </div>
        </div>
    </section>
{% endblock body %}